return {
    -- char = "▏",
    char = "│",
    filetype_exclude = {
        "help",
        "dashboard",
        "neo-tree",
        "Trouble",
        "lazy",
        "mason",
        "notify",
        "toggleterm",
    },
    indentLine_enabled = 1,
    buftype_exclude = { "terminal" },
    show_trailing_blankline_indent = false,
    show_first_indent_level = false,
    show_current_context = true,
    show_current_context_start = true,
    space_char_blankline = " ",
}
